hopefully completed debugging of new version allowing new Kafka clusters

diff --git a/kafka-1 b/kafka-1
--- a/kafka-1
+++ b/kafka-1
@@ -1,5 +1,7 @@
 #!/bin/bash
 
+# er -e 'clusters(ec2...)' -> cluster (ex: kafka701)
+
 # express Intellectual Property Rights
 cat <<EOT
 
@@ -43,67 +45,47 @@ then
 		exit 1
 	fi
 	Ipa=$( echo $AWSHost |awk -F\- '{print $NF}' |awk -F\. '{print $1"-"$2"-"$3"-"$4}' )				# get the numeric tuples as hyphenated IP address
-	Regn=$( echo $AWSHost |awk -F\- '{print $3}' )									# get 2 letter region
-	if [ "$Regn" != "US" -a "$Regn" != "AP" -a "$Regn" != "EU" -a "$Regn" != "CN" ]					# region should be "US", "AP", "EU", or "CN"
-	then
-		echo "preamble: expected US, AP, EU, or CN but got $Regn - aborting!"
-		exit 1
-	fi
-	eDC=$( cat /etc/defaultcluster )										# get the name of the default cluster for this bastion server
-	Cn=$( echo $eDC |cut -c $(( $( echo $eDC |wc -c ) -3 ))- )							# isolate the cluster number from the default cluster name
-	RCn=${!Regn}													# cluster(s) to check for IP
-	Pnodes=$( for i in $RCn;do er -e %{kafka$i} |grep $Ipa; done )							# check er using cluster #(s) and IP to get hostname(s?)
-	nPn=$( echo $Pnodes |wc -w |awk '{print $1}' )									# how many hostname(s) did we find
-	if [ $nPn -eq 0 ]												# if none found
-	then
-		echo "preamble: Cannot find a host with that IP"
-		exit 1
-	else														# got at least one
-		if [ $nPn -gt 1 ]											# if more than one
-		then
-			echo "preamble: Found $nPn nodes with that IP"
-			echo $Pnodes
-			for i in $Pnodes										# investigate all found for DF alert threshold
-			do
-				iN=$(echo $i |awk -F. '{print $2}' |sed "s/-//g")					# get non-hyphenated region ex: uswest2
-				if [ ${!iN} -ne $Cn ]									# if not in this region
-				then
-					cR=$(ssh -A -oStrictHostKeyChecking=no ${BH[${!iN}]} "ssh -A $i \"df -h |grep -i 'data' |tail -1\"")	# go via bastion host in right region to get DF info
-				else
-					cR=$(ssh -A -oStrictHostKeyChecking=no $i "df -h |grep -i 'data' |tail -1")	# can ssh directly
-				fi
-				pDf=$(echo $cR |awk '{print $5}' |awk -F\% '{print $1}')				# isolate the numric value only
-				if [ $pDf -ge $ADFL ]									# Could this be the alerting host?
-				then
-#					if [ ${!iN} -ne $Cn ]
-#					then
-#						newHost=$i
-#						echo "We will use ${BH[${!iN}]} and run kafka-1 from there"		# explain need to use bastion server in correct region
-#						break
-#					else
-						newHost=$i
-						break
-#					fi
-				fi
-			done
-			tHost=$( echo $Pnodes |grep $newHost )
-			if [ "$tHost" = "" ]
-			then
-				echo "preamble: Unable to determine correct Kafka host"
-				exit 1
-			fi
-			Pnodes=$newHost
-		fi
-	fi
-	AWSHost=$Pnodes
-echo "preamble: AWSHost=$AWSHost"
-	echo "Using $AWSHost"
-else															# we have ec2-<IP> form but still need to verify reachability
-	eDC=$( cat /etc/defaultcluster )										# get the name of the default cluster for this bastion server
-	Cn=$( echo $eDC |cut -c $(( $( echo $eDC |wc -c ) -3 ))- )							# isolate the cluster number from the default cluster name
-	R=$(echo $AWSHost |awk -F\. '{print $2}' |sed "s/-//g")
-echo "preamble: R=$R  ${!R}  Cn=$Cn  ${BH[${!R}]}"
+	iP=$( echo $AWSHost |awk -F\- '{print $NF}' )
+else
+	iP=$(echo $AWSHost |awk -F\. '{print $1}' |awk -F\- '{print $2"."$3"."$4"."$5}')
 fi
+echo "iP=$iP"
+revDig=$( dig -x $iP |grep PTR |grep ec2 |awk '{print $NF}' )
+echo "revDig=$revDig"
+ncrd=$(echo $(( $(echo $revDig |wc -c |awk '{print $1}') -2)) )
+echo "ncrd=$ncrd"
+revDig=$( echo $revDig |cut -c 1-$ncrd )
+echo "preamble: revDig=$revDig"
+clusterName=$( er -e clusters\( $revDig \))
+echo "preamble: clusterName=$clusterName"
+ncrn=$(echo $clusterName |wc -c |awk '{print $1}')
+nc=4
+tr=""
+crn=4132
+while [ "$tr" = "" ]
+do
+	nc=$(( $nc - 1 ))
+	nccn=$(( $ncrn - $nc ))
+	crn=$(echo $clusterName |cut -c $nccn- )
+	tr=$( [[ $crn =~ ^-?[0-9]+$ ]] && echo $crn )
+done
+
+echo "crn=$crn"
+nccn=$(( $nccn - 1 ))
+cpfx=$(echo $clusterName |cut -c 1-$nccn )
+echo "cpfx=$cpfx"
+# clusterName=test-kafka-dest101
+# crn=101
+# cpfx=test-kafka-dest
+AWSHost=$revDig
+echo "preamble: AWSHost=$AWSHost"
+echo "Using $AWSHost"
+#else															# we have ec2-<IP> form but still need to verify reachability
+#	eDC=$( cat /etc/defaultcluster )										# get the name of the default cluster for this bastion server
+#	Cn=$( echo $eDC |cut -c $(( $( echo $eDC |wc -c ) -3 ))- )							# isolate the cluster number from the default cluster name
+#	R=$(echo $AWSHost |awk -F\. '{print $2}' |sed "s/-//g")
+#echo "preamble: R=$R  ${!R}  Cn=$Cn  ${BH[${!R}]}"
+#fi
 
 R=$( echo $AWSHost |awk -F. '{print $2}' )										# isolate region
 
@@ -127,6 +109,7 @@ nB=$(echo ${BH[$RN]} |wc -w |awk '{print $1}')
 rI=$(echo $(( $RANDOM % $nB +1 )) )
 bastion=$(echo "${BH[$RN]}" |head -$rI |tail -1)
 echo "preamble: bastion=$bastion"
+eDC=$(cat /etc/defaultcluster)
 # here is the split.
 # if we are running from taos, then copy files and transfer to bastion server to complete the run.
 if [ "$eDC" != "bastion$RN" ]												# if this is not the bastion server (run from taos.us-east-1.xad.com)
@@ -226,7 +209,7 @@ function setVdirs
 }
 
 function getDF
-{	TMPs="df -h $DD |grep -i data |awk '{print \$5}' |awk -F% '{print \$1}'"
+{	TMPs="df -h $DD |grep -iv Filesystem |awk '{print \$5}' |awk -F% '{print \$1}'"
 	DF=$( tryTwice "$TMPs" )
 	if [ $? -eq 0 ]
 	then
@@ -299,7 +282,9 @@ function getBrokerIDs
 function getDuInfo
 {	err=0
 # get disk usage info for topic partitions.
-	P=$( tryTwice "du -h $DD |sort -h |grep -iv 'last login'" )
+	P=$( tryTwice "du -h ${DD}/ |sort -h |grep -iv 'last login'" )
+#	P=$( tryTwice "du -h $DD |sort -h" )
+echo "getDuInfo: P=$P"
 # P has all the results on one line. We need to reformat to individual lines per entry.
 	r[0]="  "                                                                                                       # spaces between the first and second part of each line
 	r[1]="
@@ -312,6 +297,7 @@ function getDuInfo
 		err=$(( $err | $? ))
 		j=$( Calc "1 - $j" )                                                                                    # flip-flop (1-0=1, 1-1=0) to switch between spaces and linefeed
 	done
+echo "getDuInfo wc-l=$( wc -l kafka_DiskUsage.out)"
 	return $err
 }
 
@@ -477,23 +463,31 @@ function checkHost
 	getDuInfo
 # now to check any topics that are 10G or larger for possible misconfigurations shown by radically different sizes.
 	nL=$( wc -l kafka_DiskUsage.out |awk '{print $1}' )
+echo "checkHost: nL=$nL"
 	if [ $nL -le 1 ];  then  echo "checkHost: no kafka partitions on this host.";  exit 1;  fi
 # get list of topics having size in the Gb range with no fractional part ( >= 10G )
 	nL2=$( Calc "$nL - 1" )
-	TL=$( head -$nL2 kafka_DiskUsage.out |grep "[0-9]G " |grep -v "[0-9]\.[0-9]" |sort -u - |awk '{print $2}' |awk -F\/ '{print $NF}' )
+echo "checkHost: scale=$scale    nL2=$nL2"
+	TL=$( head -$nL2 kafka_DiskUsage.out |grep "[0-9]$scale " |grep -v "[0-9]\.[1-9]" |sort -u - |awk '{print $2}' |awk -F\/ '{print $NF}' )
+echo "checkHost: TL=$TL"
 	if [ "$TL" = "" ];  then  echo "checkHost: Could not find any large partitions on this host.";  exit 1;  fi
+	pTL=" "
 	for i in $TL
 	do
 		TLl=$( echo $(( $( echo $i |awk -F\- '{print $NF}'|wc -c |awk '{print $1}' ) + 1 )) )			# TLl = length of $i string following the last '-' character
 		TL1=$( echo $i |wc -c |awk '{print $1}' )								# TL1 = length of $i string
 		aTLl=$( Calc "$TL1 - $TLl" )										# length of $i string up to the last '-' character
 		aTL=$( echo $i |cut -c 1-$aTLl )									# aTL = topic string up to the last '-' character
-		checkSize
+		if [ "$aTL" != "$pTL" ]
+		then
+			checkSize
+			pTL=$aTL
+		fi
 	done
 # now that we know there are no misconfiguration situations to escalate, clear out and reload DU info.
 	rm -f kafka_DiskUsage.out;  if [ -e "kafka_DiskUsage.out" ]; then return 1; fi					# remove old file or return failure
 	getDuInfo
-echo "HN=$HN"
+echo "checkHost: HN=$HN"
 # get the largest disk usage topic
 	getTopic
 	echo "checkHost: Topic: $T"
@@ -529,10 +523,10 @@ echo "HN=$HN"
 }
 
 function picker
-{	NL=$( er -e %kafka${RN} |wc -l |awk '{print $1}' )
+{	NL=$( er -e %${cpfx}${RN} |wc -l |awk '{print $1}' )
 	if [ $? -ne 0 ]
 	then
-		NL=$( er -e %kafka${RN} |wc -l |awk '{print $1}' )
+		NL=$( er -e %${cpfx}${RN} |wc -l |awk '{print $1}' )
 		jumpFail
 	fi
 	RL=$( Calc "$RANDOM % $NL" )
@@ -540,10 +534,10 @@ function picker
 	then
 		HN=$( grep amazonaws kafka_hosts.out |head -1 |awk -F: '{print $2}' )
 	else
-		HN=$( er -e %kafka${RN} |head -$RL |tail -1 )
+		HN=$( er -e %${cpfx}${RN} |head -$RL |tail -1 )
 		if [ $? -ne 0 ]
 		then
-			HN=$( er -e %kafka${RN} |head -$RL |tail -1 )
+			HN=$( er -e %${cpfx}${RN} |head -$RL |tail -1 )
 			jumpFail
 		fi
 	fi
@@ -552,9 +546,9 @@ function picker
 }
 
 function findHost
-{	HN=$( er -e %kafka${RN} |grep $H )									# start with the hostname from the email
+{	HN=$( er -e %${cpfx}${RN} |grep $H )									# start with the hostname from the email
 	echo "findHost: got er=$HN"
-	if [ $? -ne 0 ];  then  HN=$( er -e %kafka${RN} |grep $H ); echo "findHost retry er=$HN"; jumpFail;  fi	# retry on fail or die
+	if [ $? -ne 0 ];  then  HN=$( er -e %${cpfx}${RN} |grep $H ); echo "findHost retry er=$HN"; jumpFail;  fi	# retry on fail or die
 	edc=$( tryTwice "cat /etc/defaultcluster | grep -v \"Last login\"" )
 	echo "findHost: DefaultCluster: $edc"
 	ZKS=$( tryTwice "er -e %${edc}:ZK_CONNECT_STRING  | grep -v \"Last login\"" )
