more comments + location info in debugging output. also removed now unnecessary conditional in preamble.

diff --git a/kafka-1 b/kafka-1
--- a/kafka-1
+++ b/kafka-1
@@ -20,86 +20,89 @@ dN=$( dirname $0 )													# path to config file based on calling path to th
 . $dN/kafka.cfg														# source the config file
 
 
+# get affected host name
 if [ -f ~/kafkaHost ]													# if this file exists
 then
 	AWSHost=$(cat ~/kafkaHost)											# read file as name of host in trouble
 	echo "read kafkaHost=$AWSHost"											# announce it
 else															# just starting up so ..
-	echo "Please tell me the host server to check."									# for now we'll ask for hostname
+	echo "Please tell me the host server to check."									# ask for hostname
 	read AWSHost													# get input from operator
 fi
 # Ticket has:  "Host: xAd-Kafka-US-VPC-52.90.24.184"
 # we need:                        "ec2-52-90-24-184.compute-1.amazonaws.com"
+
 pre=$(echo $AWSHost |cut -c -3)												# isolate the first 3 characters
-echo "pre=$pre"
+# echo "pre=$pre"
 if [ "$pre" != "ec2" ]													# if not "ec2" then should be translated
 then
-	if [ "$pre" != "xAd" ]
+	if [ "$pre" != "xAd" ]												# should start with "xAd"
 	then
-		echo "expecting xAd- or ec2- type of server name"
+		echo "preamble: expecting xAd- or ec2- type of server name"
 		echo "aborting due to unknown type"
 		exit 1
 	fi
 	Ipa=$( echo $AWSHost |awk -F\- '{print $NF}' |awk -F\. '{print $1"-"$2"-"$3"-"$4}' )				# get the numeric tuples as hyphenated IP address
 	Regn=$( echo $AWSHost |awk -F\- '{print $3}' )									# get 2 letter region
-	if [ "$Regn" != "US" -a "$Regn" != "AP" -a "$Regn" != "EU" -a "$Regn" != "CN" ]
+	if [ "$Regn" != "US" -a "$Regn" != "AP" -a "$Regn" != "EU" -a "$Regn" != "CN" ]					# region should be "US", "AP", "EU", or "CN"
 	then
-		echo "expected US, AP, EU, or CN but got $Regn - aborting!"
+		echo "preamble: expected US, AP, EU, or CN but got $Regn - aborting!"
 		exit 1
 	fi
 	eDC=$( cat /etc/defaultcluster )										# get the name of the default cluster for this bastion server
 	Cn=$( echo $eDC |cut -c $(( $( echo $eDC |wc -c ) -3 ))- )							# isolate the cluster number from the default cluster name
-	RCn=${!Regn}
-	Pnodes=$( for i in $RCn;do er -e %{kafka$i} |grep $Ipa; done )
-	nPn=$( echo $Pnodes |wc -w |awk '{print $1}' )
-	if [ $nPn -eq 0 ]
+	RCn=${!Regn}													# cluster(s) to check for IP
+	Pnodes=$( for i in $RCn;do er -e %{kafka$i} |grep $Ipa; done )							# check er using cluster #(s) and IP to get hostname(s?)
+	nPn=$( echo $Pnodes |wc -w |awk '{print $1}' )									# how many hostname(s) did we find
+	if [ $nPn -eq 0 ]												# if none found
 	then
-		echo "Cannot find a host with that IP"
+		echo "preamble: Cannot find a host with that IP"
 		exit 1
-	else
-		if [ $nPn -gt 1 ]
+	else														# got at least one
+		if [ $nPn -gt 1 ]											# if more than one
 		then
-			echo "Found $nPn nodes with that IP"
+			echo "preamble: Found $nPn nodes with that IP"
 			echo $Pnodes
-			for i in $Pnodes
+			for i in $Pnodes										# investigate all found for DF alert threshold
 			do
-				iN=$(echo $i |awk -F. '{print $2}' |sed "s/-//g")
+				iN=$(echo $i |awk -F. '{print $2}' |sed "s/-//g")					# get non-hyphenated region ex: uswest2
 				if [ ${!iN} -ne $Cn ]									# if not in this region
 				then
 					cR=$(ssh -A -oStrictHostKeyChecking=no ${BH[${!iN}]} "ssh -A $i \"df -h |grep -i 'data' |tail -1\"")	# go via bastion host in right region to get DF info
 				else
-					cR=$(ssh -A -oStrictHostKeyChecking=no $i "df -h |grep -i 'data' |tail -1")
+					cR=$(ssh -A -oStrictHostKeyChecking=no $i "df -h |grep -i 'data' |tail -1")	# can ssh directly
 				fi
 				pDf=$(echo $cR |awk '{print $5}' |awk -F\% '{print $1}')				# isolate the numric value only
-				if [ $pDf -ge $ADFL ]
+				if [ $pDf -ge $ADFL ]									# Could this be the alerting host?
 				then
-					if [ ${!iN} -ne $Cn ]
-					then
-						echo "You must login to ${BH[${!iN}]} and run kafka-1 from there"	# explain need to use bastion server in correct region
-						exit 0
-					else
+#					if [ ${!iN} -ne $Cn ]
+#					then
+#						newHost=$i
+#						echo "We will use ${BH[${!iN}]} and run kafka-1 from there"		# explain need to use bastion server in correct region
+#						break
+#					else
 						newHost=$i
 						break
-					fi
+#					fi
 				fi
 			done
 			tHost=$( echo $Pnodes |grep $newHost )
 			if [ "$tHost" = "" ]
 			then
-				echo "Unable to determine correct Kafka host"
+				echo "preamble: Unable to determine correct Kafka host"
 				exit 1
 			fi
 			Pnodes=$newHost
 		fi
 	fi
 	AWSHost=$Pnodes
-echo "AWSHost=$AWSHost"
+echo "preamble: AWSHost=$AWSHost"
 	echo "Using $AWSHost"
 else															# we have ec2-<IP> form but still need to verify reachability
 	eDC=$( cat /etc/defaultcluster )										# get the name of the default cluster for this bastion server
 	Cn=$( echo $eDC |cut -c $(( $( echo $eDC |wc -c ) -3 ))- )							# isolate the cluster number from the default cluster name
 	R=$(echo $AWSHost |awk -F\. '{print $2}' |sed "s/-//g")
-echo "R=$R  ${!R}  Cn=$Cn  ${BH[${!R}]}"
+echo "preamble: R=$R  ${!R}  Cn=$Cn  ${BH[${!R}]}"
 fi
 
 R=$( echo $AWSHost |awk -F. '{print $2}' )										# isolate region
@@ -119,17 +122,19 @@ case "$R" in
 	"cn-north-1")		RN=$CNN1
 		;;
 esac
-echo "$R -> $RN"													# us-west-2 -> 701
+echo "preamble: $R -> $RN"													# us-west-2 -> 701
 nB=$(echo ${BH[$RN]} |wc -w |awk '{print $1}')
 rI=$(echo $(( $RANDOM % $nB +1 )) )
 bastion=$(echo "${BH[$RN]}" |head -$rI |tail -1)
-echo "bastion=$bastion"
+echo "preamble: bastion=$bastion"
+# here is the split.
+# if we are running from taos, then copy files and transfer to bastion server to complete the run.
 if [ "$eDC" != "bastion$RN" ]												# if this is not the bastion server (run from taos.us-east-1.xad.com)
 then
-	echo "Transferring to $bastion"											# announce intention to migrate
+	echo "preamble: Transferring to $bastion"											# announce intention to migrate
 	scp kafka[.-][c1]* ${bastion}:~											# copy files to bastion server
 sleep 1
-	ssh -A -oStrictHostKeyChecking=no $bastion "/bin/echo -n $AWSHost >kafkaHost"					# create kafkaHost file to pass name of problem host
+	ssh -A -oStrictHostKeyChecking=no $bastion "/bin/echo -n $AWSHost >kafkaHost"					# create kafkaHost file to pass name of problem host (line 24 above)
 sleep 1
 	ssh -A -oStrictHostKeyChecking=no $bastion ~/kafka-1								# run kafka-1 on bastion server to actually fix the problem
 sleep 1
@@ -152,7 +157,7 @@ function Calc
 function jumpFail
 {	if [ $? -ne 0 ]
 	then
-		echo "failed twice trying to execute command via jumphost"
+		echo "jumpFail: failed twice trying to execute command via jumphost"
 		echo "suggest checking remote access first, then retry script."
 		exit 1
 	fi
@@ -170,7 +175,7 @@ sleep 1
 	done
 	if [ $err -ne 0 ]
 	then
-		echo "Failed twice trying to execute command via ssh to $HN" >/dev/stderr
+		echo "tryTwice: Failed twice trying to execute command via ssh to $HN" >/dev/stderr
 		echo "Command: $1" >/dev/stderr
 		echo "Suggest checking remote access first, then retry script." >/dev/stderr
 		exit 1
@@ -191,10 +196,10 @@ function setVdirs
 	nDp=$( echo $dP |wc -w |awk '{print $1}')									# might be more than one data dir specified
 	if [ $nDp -gt 1 ]
 	then														# find the one with the most files in it
-		oNdF=0
+		oNdF=0													# start oldNumberDataFiles as zero
 		for i in $dP
 		do
-			nDf=$(tryTwice "sudo ls -al $i |wc -l |awk '{print $1}'")
+			nDf=$(tryTwice "sudo ls -al $i |wc -l |awk '{print $1}'")					# Number of Data Files
 			if [ $nDf -gt 5 ]
 			then
 				if [ $nDf -gt $oNdF ]
@@ -217,7 +222,7 @@ function setVdirs
 			DD=$dP
 		fi
 	fi
-	echo "DataDir=$DD   BinDir=$BD   ConfigDir=$CD"
+	echo "setVdirs: DataDir=$DD   BinDir=$BD   ConfigDir=$CD"
 }
 
 function getDF
@@ -227,14 +232,14 @@ function getDF
 	then
 		if [ "$DF" = "" ]
 		then
-			echo "Couldn't get DF for $DD"
+			echo "getDF: Couldn't get DF for $DD"
 			echo "Should escalate."
 			exit 0
 		fi
-		echo "$DD DF=${DF} % full"
+		echo "getDF: $DD DF=${DF} % full"
 		return 0
 	else
-		echo "problem getting DF of /data"
+		echo "getDF: problem getting DF of /data"
 		DF=-1
 		return 1
 	fi
@@ -246,7 +251,7 @@ function getTopic
 		L=$( tail -2 kafka_DiskUsage.out |head -1 )								# get largest partition
 	else
 		L=$( grep -v "${T2}-[0-9]" kafka_DiskUsage.out |tail -2 |head -1 )					# get second largest partition
-		echo "L=$L"
+		echo "getTopic: L=$L"
 	fi
 	L1=$( echo $L |awk -F/ '{print $NF}' )										# strip off directory info.
 	L2=$( echo $L |awk -F- '{print $NF}' |wc -c |awk '{print $1}' )							# number of characters after the last '-' (partition number)
@@ -276,7 +281,7 @@ function getPartitionInfo
 	testTopic=$( head -1 kafka_partitionInfo.out |awk '{print $2}' )
 	if [ "$testTopic" != "$T" ]
 	then
-		echo "Failed to get new partitionInfo for $T - got $testTopic instead."
+		echo "getPartitionInfo: Failed to get new partitionInfo for $T - got $testTopic instead."
 		return 1
 	fi
 	return $err
@@ -314,7 +319,7 @@ function isItRebuilt
 {	fE=$( tryTwice "sudo su - xad -c \"ls ${DD}/* |grep $REBUILT\" |egrep -iv 'last login|no such file'" )
 	if [ "$fE" != "" ]												# if the edge case flag file exists
 	then
-		echo "This seems to be a special case where the host was rebuilt."
+		echo "isItRebuilt: This seems to be a special case where the host was rebuilt."
 		echo "You should do this by hand, as I am not yet equipped to handle it."
 		exit 0													# can return zero to handle normally
 	fi
@@ -367,7 +372,7 @@ echo "Checking sizes for $aTL"
 		HN=$OHN													# back to the problem host
 		S=$( grep "/${aTL}-[0-9]" kafka_DiskUsage.out |awk '{print $1}' )					# get Sizes for this topic
 		m=$( echo $S |wc -w |awk '{print $1}' )									# number of Sizes found
-		if [ $m -lt 2 ]; then  echo "Failed to get more than 1 partition";  exit 0;  fi				# verify we now have more than one size
+		if [ $m -lt 2 ]; then  echo "checkSize: Failed to get more than 1 partition";  exit 0;  fi				# verify we now have more than one size
 	fi
 # split size into number and scale
 	j=0
@@ -394,7 +399,7 @@ echo "Checking sizes for $aTL"
 		then
 # echo "${SC[$i]} not eq ${SC[$n]}"
 			isItRebuilt
-			echo "partition sizes too far apart"
+			echo "checkSize: partition sizes too far apart"
 			echo "Need to escalate!"
 			exit 0
 		fi
@@ -420,7 +425,7 @@ echo "Checking sizes for $aTL"
 			isItRebuilt
 			if [ $? -eq 1 ]
 			then
-				echo "Need to escalate!"
+				echo "checkSize: Need to escalate!"
 				echo "partition sizes too far apart"
 				exit 0
 			fi
@@ -438,29 +443,29 @@ function checkHost
 		getDF													# so this makes 4 attempts
 		if [ $DF -eq -1 ]
 		then
-			echo "Failed to get \"Disk Full\" info: DF=$DF"
+			echo "checkHost: Failed to get \"Disk Full\" info: DF=$DF"
 			exit 1
 		fi
 	fi
 	if [ $DF -lt $ADFL ]
 	then
-		echo "This disk usage shows less than ${ADFL}% used DF=${DF}%."
+		echo "checkHost: This disk usage shows less than ${ADFL}% used DF=${DF}%."
 		echo "The alert may have already cleared."
 		exit 0
 	fi
 	if [ $DF -gt $UDFL ]
 	then
-		echo "This disk is more than ${UDFL}% full. DF=${DF}%"
+		echo "checkHost: This disk is more than ${UDFL}% full. DF=${DF}%"
 		echo "We can try to do the procedure, or you might want to escalate to xAd immediately."
 		echo "Shall we proceed ( y or n )?"
 		read Reply
 		case "$Reply" in
-		"n" | "N")	echo "OK - Please escalate."
+		"n" | "N")	echo "checkHost: OK - Please escalate."
 				exit 0
 			;;
-		"y" | "Y")	echo "Proceeding"
+		"y" | "Y")	echo "checkHost: Proceeding"
 			;;
-		*)		echo "You really should quit trying to jerk my chain."
+		*)		echo "checkHost: You really should quit trying to jerk my chain."
 				exit 1
 			;;
 		esac
@@ -472,11 +477,11 @@ function checkHost
 	getDuInfo
 # now to check any topics that are 10G or larger for possible misconfigurations shown by radically different sizes.
 	nL=$( wc -l kafka_DiskUsage.out |awk '{print $1}' )
-	if [ $nL -le 1 ];  then  echo "no kafka partitions on this host.";  exit 1;  fi
+	if [ $nL -le 1 ];  then  echo "checkHost: no kafka partitions on this host.";  exit 1;  fi
 # get list of topics having size in the Gb range with no fractional part ( >= 10G )
 	nL2=$( Calc "$nL - 1" )
 	TL=$( head -$nL2 kafka_DiskUsage.out |grep "[0-9]G " |grep -v "[0-9]\.[0-9]" |sort -u - |awk '{print $2}' |awk -F\/ '{print $NF}' )
-	if [ "$TL" = "" ];  then  echo "Could not find any large partitions on this host.";  exit 1;  fi
+	if [ "$TL" = "" ];  then  echo "checkHost: Could not find any large partitions on this host.";  exit 1;  fi
 	for i in $TL
 	do
 		TLl=$( echo $(( $( echo $i |awk -F\- '{print $NF}'|wc -c |awk '{print $1}' ) + 1 )) )			# TLl = length of $i string following the last '-' character
@@ -491,7 +496,7 @@ function checkHost
 echo "HN=$HN"
 # get the largest disk usage topic
 	getTopic
-	echo "Topic: $T"
+	echo "checkHost: Topic: $T"
 	NT=$( grep "${T}-[0-9]" kafka_DiskUsage.out |wc -l |awk '{print $1}' )						# number of entries for this topic
 	if [ $NT -lt 2 ]
 	then
@@ -548,11 +553,12 @@ function picker
 
 function findHost
 {	HN=$( er -e %kafka${RN} |grep $H )									# start with the hostname from the email
-	if [ $? -ne 0 ];  then  HN=$( er -e %kafka${RN} |grep $H );  jumpFail;  fi				# retry on fail or die
+	echo "findHost: got er=$HN"
+	if [ $? -ne 0 ];  then  HN=$( er -e %kafka${RN} |grep $H ); echo "findHost retry er=$HN"; jumpFail;  fi	# retry on fail or die
 	edc=$( tryTwice "cat /etc/defaultcluster | grep -v \"Last login\"" )
-	echo "DefaultCluster: $edc"
+	echo "findHost: DefaultCluster: $edc"
 	ZKS=$( tryTwice "er -e %${edc}:ZK_CONNECT_STRING  | grep -v \"Last login\"" )
-	echo "ZooKeeperConnectString: $ZKS"
+	echo "findHost: ZooKeeperConnectString: $ZKS"
 	c=0
 	checkHost
 	while [ $? != 0 ]
@@ -560,7 +566,7 @@ function findHost
 		c=$( Calc "$c + 1" )
 		if [ $c -eq 3 ]
 		then
-			echo "Did not find host with more than one $T partition"
+			echo "findHost: Did not find host with more than one $T partition"
 			echo "Suggest escalate to xAD"
 			echo "Alternatively, re-run the script or try manually"
 			exit 0
@@ -585,12 +591,12 @@ function getRetentionValue
 }
 
 function setRetentionValue
-{	echo "$( date ): I am going to change the retention time of $T from $RV to $NRV"
+{	echo "setRetentionValue $( date ): I am going to change the retention time of $T from $RV to $NRV"
 	SRV=$( tryTwice "sudo su - xad -c '${BD}/kafka-topics.sh --zookeeper $ZKS --topic $T --alter --config retenention.ms=${NRV} '"  )
 }
 
 function resetRV
-{	echo "$( date ): I am going to restore the retention value of $T from $NRV to $RV"
+{	echo "resetRV $( date ): I am going to restore the retention value of $T from $NRV to $RV"
 	SRV=$( tryTwice "sudo su - xad -c '${BD}/kafka-topics.sh --zookeeper $ZKS --topic $T --alter --config retenention.ms=${RV} '"  )
 }
 
@@ -612,7 +618,7 @@ function lvlDown
 
 function getSecs													# get number of seconds since 1/1/1900_00:00
 {	ct=$( date "+%s" )
-	echo "LR=$LR   ct=$ct"
+	echo "getSecs: LR=$LR   ct=$ct"
 }
 
 function waitTime
@@ -624,10 +630,11 @@ function tryFix														# see if we can adjust the retention value
 	NRV=$( Calc "$RV - ( ( $RV * $retentionTimeDelta ) / 100 )" )							# New Retention Value
 	if [ $NRV -le 0 -o $NRV -ge $RV ]
 	then
-		echo "new retention not acceptable"
+		echo "tryFix: new retention not acceptable"
 		echo "current value: $RV"
 		echo "new retention: $NRV"
 		echo "Do not know how to proceed"
+		echo "Must escalate to xAd."
 		exit 1
 	fi
 
@@ -652,7 +659,7 @@ EOT
 	read Reply													# do not care what it is.
 	getSecs
 	ctis=$ct
-	echo "$ctis" >last_run.txt
+	echo "tryFix: $ctis" >last_run.txt
 
 # ask the operator if OK to make change.
 	cat <<EOT
@@ -661,29 +668,29 @@ I can change the RetentionValue from $RV to $NRV if you like.
 EOT
 	read Reply
 	case "$Reply" in
-	"Y" | "y")	echo "Please confirm your answer again:(Y or N)"
+	"Y" | "y")	echo "tryFix: Please confirm your answer again:(Y or N)"
 			read Reply2
 			case "$Reply2" in
-			"Y" | "y")	echo "do the deed"
+			"Y" | "y")	echo "tryFix: do the deed"
 					setRetentionValue
 				;;
-			"N" | "n")	echo "Canceling the intent to make changes."
+			"N" | "n")	echo "tryFix: Canceling the intent to make changes."
 					if [ $Lvl -eq 1 ]; then exit 0; fi						# nothing more to be done
 					lvlDown
 					getDF
 				;;
-			*)		echo "STOP THAT!!!!"
+			*)		echo "tryFix: STOP THAT!!!!"
 					if [ $Lvl -eq 1 ]; then exit 1; fi
 					lvlDown
 					getDF
 			esac
 		;;
-	"N" | "n")	echo "OK - I won't make any changes."
+	"N" | "n")	echo "tryFix: OK - I won't make any changes."
 			if [ $Lvl -eq 1 ]; then exit 0; fi								# nothing more to be done
 			lvlDown
 			getDF
 		;;
-	*)		echo "Don't EVER do that again!!!!"
+	*)		echo "tryFix: Don't EVER do that again!!!!"
 	esac
 }
 
@@ -695,12 +702,12 @@ EOT
 HN=$AWSHost
 sleep 1
 B=$( tryTwice "pwd" )													# verify that we can reach this host
-if [ "$B" != "/home/$USER" ];  then  echo "could not connect to $AWSHost";  exit 0;  fi					# check expected return string
+if [ "$B" != "/home/$USER" ];  then  echo "main: could not connect to $AWSHost";  exit 0;  fi					# check expected return string
 H=$AWSHost														# we'll attempt to use this as our initial host
 rm -f kafka_connect.txt													# remove old file for appending new info
 if [ -e "kafka_connect.txt" ]; then exit 1; fi
 findHost														# find host where we can verify and adjust
-echo "Using kafka host $HN"												# Got a good host
+echo "main: Using kafka host $HN"												# Got a good host
 tryFix															# see if we can proceed
 
 # at this point we should have altered the retention value of the largest partition(s)
@@ -720,7 +727,7 @@ then															# good to continue
 	while [ $DF -gt $ADFL -a $ct -lt $quitTime ]
 	do
 		LR=$( Calc "$ct + $sleepTime" )										# set next wait time
-		echo "DF=$DF %"
+		echo "main: DF=$DF %"
 		waitTime												# wait for next check
 		if [ $Lvl -eq 1 ]
 		then
@@ -745,14 +752,14 @@ then															# good to continue
 	getDF
 	if [ $DF -gt 0 ]
 	then
-		echo "Data Volume = $DF %used"										# closing display of disk usage
+		echo "main: Data Volume = $DF %used"										# closing display of disk usage
 	fi
 	if [ $DF -ge $ADFL ]
 	then
-		echo "Failed to reduce the data volume size below alert threshold"
+		echo "main: Failed to reduce the data volume size below alert threshold"
 		echo "Must escalate to xAd."
 	fi
 else															# tryFix returned error
-	echo "Something went wrong. Please investigate."
+	echo "main: Something went wrong. Please investigate."
 	echo "Then either re-try or escalate."
 fi
